export const traipseLyrics = [
  "I dropped in unannounced",
  "I dropped unexpectedly",
  "and you looked right through me",
  "you looked right on through",
  "but it didn’t hurt babe",
  "naw it didn’t hurt",
  " ",
  "eventually I came back around",
  "we drank the water and the wine",
  "surprised at how the walls",
  "moved around the room",
  "and all their flowers too",
  " ",
  "through the traipse of youth",
  "through the fog and the perfume",
  "knocked out and over by a passing glance",
  "by a look thrown across the room",
  " ",
  "how it stops you in your tracks unmade",
  "and we go all aglow and ablaze",
  "as an image in the eye held shut",
  "on a sunny day as neon at dawn",
  "shutters and sways",
  " ",
  "and we sink like stones in water",
  "as the ground gives out all hot and bothered",
  " ",
  "(who chooses to fall)",
  "through the traipse of youth",
  "(who chooses who)",
  "through the fog and the perfume",
  "(who chooses to fall)",
  "cartoonish birds",
  "(who chooses to lose their cool)",
  "all aflutter",
  " ",
  "as in a dream where",
  "the ground met me",
  "a little too fast and rosy eyed",
  "stars seemed small and",
  "I seemed to myself",
  "another a true lover",
  "a real coin",
  "falling in the well",
  " ",
  "(who chooses to fall)",
  "through the traipse of youth",
  "(who chooses who)",
  "through the fog and the perfume",
  "(who chooses to fall)",
  "cartoonish birds",
  "(who chooses to lose their cool)",
  "all aflutter",
  " ",
  "who chooses to fall",
  "who chooses who",
  "who chooses to fall",
  "who chooses to lose their cool"
]

export const spokaneLyrics = [
  "I lost the train somewhere between Spokane and Poughkeepsie somehow I found my way after all any way like a hound a duck or myself right after one long hard look all around the house for a single goddamned vanity mirror in each one of about a thousand nine rooms so you couldn’t actually blame me for being as late as I was but I finally found it on the wall of a room with no door and four or five windows sometime after it occurred to me that I should come in through the garden",
  " ",
  "there’s more than enough ways out and back but",
  " ",
  "everyone seems to agree we’re in line and we’re waiting",
  "and when we get there everything’ll feel so complete but waiting around never got me where I’m going",
  "and everyone seems to believe their time's coming like",
  " ",
  "not the train itself rather everything that you could ever hope to find lying on it car after car never rearranged from caboose to destination from where I’m standing to you whether or not the track splits in two or that’s not where you’re going I promise you’ll get there in style like your mother in-law’s Mercedes Benz or Rick Van Shaw’s blue Chelsea boot",
  " ",
  "everyone seems to agree we’re in line and we’re waiting",
  "and when we get there everything’ll feel so complete",
  "but waiting around never got me where I’m going",
  "everyone seems to believe their time’s coming their patience is their virtue",
  "but everyone seems to agree it's their insistence that'll bring their pleasure",
  " ",
  "I think it was after we crossed the chesapeake right north the deltas or any other city you’ve heard of when I heard a shout and, curious, walked through the bar which was something else like an old west saloon in New Carolina with a bar keep who’s got the pours your grand-dad asks twice for shouting in the smoky din like the conductor, wherever he is, god bless him"
]