export const traipseLyrics = [
  "I dropped in unannounced",
  "I dropped unexpectedly",
  "and you looked right through me",
  "you looked right on through",
  "but it didn’t hurt babe",
  "naw it didn’t hurt",
  " ",
  "eventually I came back around",
  "we drank the water and the wine",
  "surprised at how the walls",
  "moved around the room",
  "and all their flowers too",
  " ",
  "through the traipse of youth",
  "through the fog and the perfume",
  "knocked out and over by a passing glance",
  "by a look thrown across the room",
  " ",
  "how it stops you in your tracks unmade",
  "and we go all aglow and ablaze",
  "as an image in the eye held shut",
  "on a sunny day as neon at dawn",
  "shutters and sways",
  " ",
  "and we sink like stones in water",
  "as the ground gives out all hot and bothered",
  " ",
  "(who chooses to fall)",
  "through the traipse of youth",
  "(who chooses who)",
  "through the fog and the perfume",
  "(who chooses to fall)",
  "cartoonish birds",
  "(who chooses to lose their cool)",
  "all aflutter",
  " ",
  "as in a dream where",
  "the ground met me",
  "a little too fast and rosy eyed",
  "stars seemed small and",
  "I seemed to myself",
  "another a true lover",
  "a real coin",
  "falling in the well",
  " ",
  "(who chooses to fall)",
  "through the traipse of youth",
  "(who chooses who)",
  "through the fog and the perfume",
  "(who chooses to fall)",
  "cartoonish birds",
  "(who chooses to lose their cool)",
  "all aflutter",
  " ",
  "who chooses to fall",
  "who chooses who",
  "who chooses to fall",
  "who chooses to lose their cool"
]

export const firstCar = [
  "my first car’s still driving without me",
  "blasting the early 2000s on repeat",
  "static love songs from some iPod over FM",
  "sunroof rolled, headlights low, it’s driving",
  " ",
  "I watch it passing just as startled" ,
  "as when making eye-contact",
  "through a neighbor's window",
  "and I realize it’s just some" ,
  "poster of an actor I don’t know", 
  " ",
  "epiphany after epiphany",
  "I feel like I’m sitting",
  "in the middle of the street",
  " ",
  "epiphany after epiphany",
  "I might as well be sitting",
  "in the middle of the street",
  " ",
  "my first car's gone a long way some hundred K",
  "trolling this forgotten city without me",
  "full of lights and sounds new and old",
  "among people and places that I used to know",
  "yeah my first car it’s still driving",
  " ",
  "but you don’t see me",
  "and I feel like I’m sitting",
  "right in the back seat",
  " ",
  "epiphany after epiphany",
  "I see it and know I’m going",
  "I see it and know when I get there",
  " ",
  "I’m there to stay",
  "I’m there to stay",
  " ",
  "nowhere near where you'd think",
  "nowhere near where you’d think",
  "but I do hope you’re still kicking without me",
  "nowhere near where you'd think",
  "nowhere near where you’d think"
]

export const spokaneLyrics = [
  "I lost the train somewhere between Spokane and Poughkeepsie somehow I found my way after all any way like a hound a duck or myself right after one long hard look all around the house for a single goddamned vanity mirror in each one of about a thousand nine rooms so you couldn’t actually blame me for being as late as I was but I finally found it on the wall of a room with no door and four or five windows sometime after it occurred to me that I should come in through the garden",
  " ",
  "there’s more than enough ways out and back but",
  " ",
  "everyone seems to agree we’re in line and we’re waiting",
  "and when we get there everything’ll feel so complete but waiting around never got me where I’m going",
  "and everyone seems to believe their time's coming like",
  " ",
  "not the train itself rather everything that you could ever hope to find lying on it car after car never rearranged from caboose to destination from where I’m standing to you whether or not the track splits in two or that’s not where you’re going I promise you’ll get there in style like your mother in-law’s Mercedes Benz or Rick Van Shaw’s blue Chelsea boot",
  " ",
  "everyone seems to agree we’re in line and we’re waiting",
  "and when we get there everything’ll feel so complete",
  "but waiting around never got me where I’m going",
  "everyone seems to believe their time’s coming their patience is their virtue",
  "but everyone seems to agree it's their insistence that'll bring their pleasure",
  " ",
  "I think it was after we crossed the chesapeake right north the deltas or any other city you’ve heard of when I heard a shout and, curious, walked through the bar which was something else like an old west saloon in New Carolina with a bar keep who’s got the pours your grand-dad asks twice for shouting in the smoky din like the conductor, wherever he is, god bless him"
]

export const funk = [
  "tough enough", 
  "to pull us both from a funk",
  "why try",
  "if it feels alright",
  "socks off",
  "into oblivion",
  "but tough enough",
  "to pull us both out of a mood",
  " ",
  "like two old birds",
  "knocked right out of the blue",
  "spiraling down",
  "over", 
  " ",
  "what we had however tangible",
  "you could try to",
  " ",
  "call it back by any other name",
  "why try to maintain understanding",
  "of kismet and circumstance",
  "as a fact ever-changing",
  " ",
  "cut loose",
  "like a punk on a bad hair day",
  "pulls out her pin",
  "and leaves him shaking",
  "in his boots", 
  "caffeinated and uncomfortable",
  "but still tough enough",
  "to pull them both from a funk",
  " ",
  "what they have however attainable",
  "you could try to",

  "call it back by any other name",
  "those closest still maintain their understanding",
  "of each of us as a fact ever",
  "ever changing",
  " ",
  "call it back",
  "no matter how it went down",
  "why try to maintain kismet and circumstance",
  "as facts never changing"
]

export const soft = [
  "she’s the one",
  "in the leather jacket",
  "she’s the one holding",  
  "the soft spot heavy-handed",
  " ",
  "takes you by the arm",
  "tells you where to go",
  "says you’re the only one",
  "calls you a party animal", 
  "calls your money liminal",
  `asks, "honey, will you follow?"`,
  " ",
  "when we go dancing",
  "and sway so close", 
  "soft in your ear her voice and rose",
  " ",
  "so you go",
  "in through this cellar door",
  "where she knows every single secret",
  "code",
  "and the room goes dark but for",
  "a single bulb dangling over the microphone",
  "pointed at the loudest speaker cone",
  "where you stand and for a moment",
  "you think you see",
  " ",
  "everyone you’ve ever known",
  "dancing and swaying so close",
  "soft in your ear her voice and rose",
  "perfume after midnight",
  "and after the show",
  "I say we go dancing",
  " ",
  "step back",
  "breathe in",
  "let it be",
  "unending",
  "let it be",
  "everything",	
  " ",
  "take me seriously",
  "wherever you choose to go",
  "I’ll be the cat to your string",
  "I’ll be the diamond on your chandelier",
  "I’ll be your bouquet of flowers burning",
  "cause I’m in love",
  "with everyone you know",
  " ",
  "the way we go dancing",
  "and sway so close soft",
  "in your ear her voice and rose",
  "perfume after midnight",
  "and after the show",
  "I say we go dancing",
  " ",
  "step back",
  "breathe in",
  "let it be",
  "unending",
  "let it be",
  "everything"
]

export const nextToMe = [
  "knowing the middle and the end",
  "at the beginning but unable",
  "to grasp more than two at once",
  "I mute the TV and plant my head in the couch",
  " ",
  "knowing more or less than I care to",
  "I'd rather talk about the weather",
  "it's just been so cold",
  "and I'm sweating in the house",
  " ",
  "yeah I'd shower in the yard and piss",
  "the neighbors off my legs",
  "look fucking awesome in these swim trunks",
  "and I've gotten kind of tan",
  " ",
  "so why would I want anything",
  "why would I want to do anything",
  "but lie in the lawn",
  "when there’s dishes to be done",
  "and the garden’s overgrown",
  " ",
  "why would I want anything",
  "but to lie in the lawn",
  "the grass at our knees",
  "hair weaved into weeds",
  "just spilling out like vines",
  "on a wall",
  " ",
  "why would I want to do anything",
  "but lie in the lawn",
  "in silence watching dry lightning",
  "the dew on our backs",
  "the dirt at our ears",
  "and all the lights",
  "in the house still on",
  " ",
  "why would I want anything",
  "why would I want to do anything",
  "but lie in the lawn",
  "when there's dishes to be done",
  "and the garden's overgrown",
  "and there's cans of paint leaking in the garage",
  "yeah the garden's overgrown",
  "and there's cans of paint leaking in the garage",
  " ",
  "the concrete'll still be",
  "stained green and pink",
  "when the cans of paint are gone",
  " ",
  "so why would I want anything",
  "why would I want to do anything",
  "but lie in the lawn in silence",
  "watching dry lightning",
  "with your mirage",
  "flashing next to me",
  "next to me",
  " ",
  "there and gone"
]

export const light = [
  "light this house up",
  "I remember where everything should be",
  "pick a record put it on",
  "why don’t you turn on some slow TV",
  " ",
  "light this house up",
  "let all the empty boxes be",
  "sweep the floors drop the rug",
  "let in the cool night breeze",
  " ",
  "light this house up",
  "let all the neighbors see",
  "every photograph on the wall",
  "all our furniture, everything",
  " ",
  "light this house up",
  "I remember where everything goes",
  "light this house up",
  "I remember everything",
  " ",
  " ",
  "infrared, borealis, from the end of the tunnel",
  "fluorescent, fire, lime",
  "neon, halogenic, bioluminescent",
  "everlasting, in your eyes",
  "ultraviolet, LED, given the green",
  "metal halide, black, traffic, as a feather",
  "the sun, moon, street, strobe, etcetera",
  " ",
  "like the city in full color on your favorite holiday", 
  "like the first sunny day after the season’s first decent snowfall", 
  "like a bumbling shadow over running water", 
  "like the liquid spilling from a broken glow-stick", 
  "like the fridge open at midnight", 
  "like a lamp in a window seen in passing",
  "like a red coat in a dimly lit room", 
  "like the last big act on broadway",
  "like an obvious illusion", 
  "like an obvious illusion",
  "like a theater after the credits have rolled"
]

export const daybreaker = [
  "blank-slated right on out of it",
  "I've been",
  "straight up sun circling like all my",
  "time has sped up and been spent",
  "I’m hard lined",
  "straight up racing for the gate",
  " ",
  "blank-slated right on out of it",
  "I am",
  "a nocturnal animal at high noon",
  "I’m not scared or frightened of",
  "shadows",
  "but this one’s gotten a little too", 
  "familiar",
  " ",
  "even the moon don’t try to hide it",
  "what may",
  "wake you from the night crying out your",
  "name all hot-hearted crooning like",
  "every",
  "single ghost in your childhood home",
  " ",
  "is it following me",
  "or just waiting round the bend",
  "hanging out with all my closest friends",
  "is it following me or",
  "sitting in wait counting down the days",
  "been there for ages anyway",  
  " ",
  "don’t try and call it love though",
  "each star",
  "whether worshiped right or set low burning under",
  "jetstreams, skylines, or sunny thunder",
  "you run",
  "your orbit among all the others",
  " ",
  "and you could lose yourself",
  "to just about anything at all but",
  "time will wait for each of us",
  "to see just what it was",
  "we lost",
  " ",
  "is it following me or", 
  "just waiting around the bend",
  "hanging out with all my oldest friends",
  "is it following me or", 
  "sitting in wait counting down the days",
  "been there for ages anyway",
  " ",
  "is it following me or", 
  "just waiting around the bend",
  "hanging out with all my closest friends",
  "is it following me or", 
  "sitting in wait counting down the days",
  "been there for ages anyway",
]

export const hung = [
  "hung by the hook", 
  "but how long's it been",
  "since you wanted it",
  "any other way",
  " ",
  "done by the book",
  "a thin line between", 
  "how you want it",
  "no other way",
  " ",
  "to say it straight to catch you",
  "outright or off-guard",
  "I can't see it",
  "any other way",
  "no other way",
  "to break the hold",
  "no other way",
  "to hold a baby",
  "no other way",
  "babe, I'm going no other way",
  " ",
  "hung by the hook",
  "a heavy line over you",
  "and over again",
  "something to swing to",
  "sway or swoon to",
  " ",
  "if I drew a line",
  "from here the way you wanted it to go",
  "would you follow",
  "or hung by the hook are you pulled through",
  "some",
  "foggy understanding",
  "of another way",
  " ",
  "to confound expectation",
  "no other way",
  "to hold a baby",
  "any other way",
  "to reiterate, I've said it once",
  "another way",
  "to say it again would be frustrating at the very least",
  "but mostly repetitive",
  "any other way",
  "to say it straight to catch you",
  "outright or off-guard",
  "I can't",
  "I can't",
  " ",
  "any other way",
  "to read a book teach me",
  "another way",
  "to fish man, I'm dying here",
  "another way",
  "to the river would probably take longer",
  "any other way",
  "I'll follow I promise",
  "another way",
  "to say it straight",
  "another way",
  "to catch you outright or off-guard",
  "another way",
  "I can't see it",
  "any other way",
  "look!",
  " ",
  "I'm confounded, I'm distraught, I'm hung",
  " ",
  "to say it straight",
  "to catch you outright or off-guard",
  "I can't see it",
  "any other way"
]

export const anymore = [
  "with your eyes closed",
  "you still hit the mark",
  "with your hands over your ears",
  "you can repeat back anything perfectly",
  "with your mouth shut",
  "you could tear down any standing man",
  " ",
  "with your eyes shut",
  "you see in the dark",
  "with your hands over your ears",
  "you can recite back anything ever said",
  "with your mouth closed",
  "you could tear down any man left standing",
  " ",
  "when I found you here when I",
  "when I found you yeah",
  "I was looking for something else I was",
  "looking for something else",
  " ",
  "but I found you yeah",
  "yeah I found you here",
  "and I’m glad I did",
  "yeah I’m glad I did",
  " ",
  "he told me",
  "I’d find you by the way it rains",
  "he told me",
  "there ain’t no other way to say it",
  " ",
  "with your mouth shut",
  "you still hit the mark",
  "with your hands over your ears",
  "you hear it before it’s even said",
  "with your eyes closed",
  "you could tear down any man still standing",
  " ",
  "when I found you here when I",
  "when I found you yeah",
  "I was looking for something else I was",
  "looking for something else",
  " ",
  "but I found you here",
  "yeah I found you here",
  "and I’m glad I did",
  "yeah I’m glad I did",
  " ",
  "now I’m not looking anymore I’m not",
  "looking anymore",
  "with my eyes shut",
  "I can still find my way to your front door",
  "I’m not listening anymore, I’m not",
  "listening anymore",
  "with my hands over my ears",
  "I can still hear the sound of your voice",
  "it’s all I listen to anymore",
  "it’s all I listen to anymore"
]

export const lavender = [
  "first thing in the morning",
  "I start digging holes in the bed",
  "as if this weed were some",
  "willow weeping over me",
  "wild eyed waking up at the foot",
  "covered in branch and vine I",
  "realized I’d never reach", 
  "every root",
  " ",
  "so I drowned the garden",
  "yeah I drowned the garden",
  " ",
  "So color me in sundry dirt",
  "in dizzy kisses woodstalk", 
  "all down my spine", 
  "as new seeds over old roots", 
  "a leaf with no a branch",
  "a tree ready for fire", 
  "for wilderness with no end",
  " ",
  "some things bloom despite me",
  "as I drown the garden",
  "some things bloom despite me",
  "some things bloom",
  "as I drown the garden",
  "yeah, as I drown the garden",
  "lavender rabbits fill the room",
]